service: harkenorc

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    autostart: false
    lambda:
      mountCode: false

functions:
  orderCallback:
    handler: handler.orderCallback
    environment:
      ENVIRONMENT: ${self:provider.stage}
      REGION: ${self:provider.region}
      AP_QUEUE_URL:
        Ref: ApQueue
    events:
      - http:
          path: order_callback
          method: post

resources:
  Conditions:
    IsLocal: !Equals ["${self:provider.stage}", "local"]

  Resources:
    ApQueue:
      Type: AWS::SQS::Queue
      Condition: IsLocal
      Properties: {}

  Outputs:
    ApQueueUrl:
      Description: "URL of the ApQueue SQS queue"
      Condition: IsLocal
      Value:
        Ref: ApQueue
