version: "3.8"
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      - SERVICES=sqs,lambda,apigateway
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
